apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculater
  namespace: jenkin

spec:
  replicas: 1

  selector:
    matchLabels:
      app: calculater

  template:
    metadata:
      labels:
        app: calculater

    spec:
      containers:
        - name: calculater
          image: abhi7677/calculater:19
          ports:
            - containerPort: 8084
